import random
songs = {
    "Bohemian Rhapsody": "Happy",
    "Hello": "Sad",
    "Happy": "Happy",
    "Rolling in the Deep": "Sad",
    "Uptown Funk": "Happy",
    "Someone Like You": "Sad",
    "Shape of You": "Happy",
    "Let It Be": "Happy",
    "Fix You": "Sad",
    "Happier": "Happy",
    "Here Comes the Sun": "Happy",
    "Yesterday": "Sad",
    "Don't Worry, Be Happy": "Happy",
    "Wake Me Up When September Ends": "Sad",
    "I Will Always Love You": "Sad",
    "Dancing Queen": "Happy",
    "The Sound of Silence": "Sad",
    "Sweet Caroline": "Happy",
    "Unchained Melody": "Sad",
    "I Wanna Dance with Somebody": "Happy",
    "Tears in Heaven": "Sad",
    "Livin' on a Prayer": "Happy",
    "Everybody Hurts": "Sad",
    "Walking on Sunshine": "Happy",
    "My Heart Will Go On": "Sad",
    "Don't Stop Believin'": "Happy",
    "Mad World": "Sad",
    "I Gotta Feeling": "Happy",
    "All of Me": "Sad",
    "Happy Together": "Happy",
    "Bridge Over Troubled Water": "Sad",
    "I Want to Hold Your Hand": "Happy",
    "The Winner Takes It All": "Sad",
    "Can't Stop the Feeling!": "Happy",
    "Yesterday Once More": "Sad",
    "I'm Yours": "Happy",
    "A Thousand Years": "Sad",
    "I'm a Believer": "Happy",
    "Hallelujah": "Sad",
    "I Will Survive": "Happy",
    "Someone You Loved": "Sad",
    "Hey Jude": "Happy",
    "The Scientist": "Sad",
    "September": "Happy",
    "Hurt": "Sad",
    "Dancing in the Moonlight": "Happy",
    "Everybody Wants to Rule the World": "Sad",
    "Brown Eyed Girl": "Happy",
    "Wish You Were Here": "Sad",
    "Good Vibrations": "Happy",
    "Yesterday": "Sad",
    "Can't Help Falling in Love": "Happy",
    "Every Breath You Take": "Sad",
    "I Feel Good": "Happy",
    "Fast Car": "Sad",
    "Walking on Sunshine": "Happy",
    "I Want to Break Free": "Sad",
    "Twist and Shout": "Happy",
    "Creep": "Sad",
    "Eye of the Tiger": "Happy",
    "Someone Like You": "Sad",
    "Hey Ya!": "Happy",
    "Love Will Tear Us Apart": "Sad",
    "Killing in the Name": "Angry",
    "Break Stuff": "Angry",
    "Given Up": "Angry",
    "The Beautiful People": "Angry",
    "Bodies": "Angry",
    "Chop Suey!": "Angry",
    "Bombtrack": "Angry",
    "Faint": "Angry",
    "You Oughta Know": "Angry",
    "Killing Me Softly With His Song": "Sad",
    "In The End": "Angry",
    "Down With The Sickness": "Angry",
    "Bulls on Parade": "Angry",
    "I Hate Everything About You": "Angry",
    "Before I Forget": "Angry",
    "The Fight Song": "Angry",
    "I Will Be Heard": "Angry",
    "Psychosocial": "Angry",
    "Freak On a Leash": "Angry",
    "Numb": "Sad",
    "My Own Summer (Shove It)": "Angry",
    "Animal I Have Become": "Angry",
    "Sober": "Sad",
    "Bleed It Out": "Angry",
    "Downfall": "Sad",
    "Du Hast": "Angry",
    "Black": "Sad",
    "Given Up": "Angry",
    "B.Y.O.B.": "Angry",
    "Wake Up": "Sad",
    "Boulevard of Broken Dreams": "Sad",
    "The Diary of Jane": "Angry",
    "One Step Closer": "Angry",
    "The Pretender": "Angry",
    "My Last Breath": "Sad",
    "Losing My Religion": "Sad",
    "Lithium": "Sad",
    "Plush": "Sad",
    "Crawling": "Angry",
    "Gone Away": "Sad",
    "Chop Suey!": "Angry",
    "In the End": "Angry",
    "Down with the Sickness": "Angry",
    "Numb": "Sad",
    "Crawling in the Dark": "Angry",
    "Everlong": "Sad",
    "Love of My Life": "Sad",
    "Basket Case": "Angry",
    "Boulevard of Broken Dreams": "Sad",
    "Don't Speak": "Sad",
    "Wrecking Ball": "Sad",
    "Paranoid": "Angry",
    "F*** You": "Angry",
    "Best of You": "Angry",
    "Stairway to Heaven": "Sad",
    "All the Small Things": "Happy",
    "Teenage Dirtbag": "Sad",
    "I Hate Everything About You": "Angry",
    "Smells Like Teen Spirit": "Angry",
    "Iris": "Sad",
    "Wonderwall": "Sad",
    "Zombie": "Angry",
    "Somebody to Love": "Happy",
    "Hotel California": "Sad",
    "Youth Gone Wild": "Angry",
    "Crazy": "Sad",
    "With or Without You": "Sad",
    "Zombie": "Angry",
    "Dream On": "Sad",
    "Bitter Sweet Symphony": "Sad",
    "Livin' on a Prayer": "Happy",
    "Dancing Queen": "Happy",
    "Under the Bridge": "Sad",
    "My Immortal": "Sad",
    "Sweet Child o' Mine": "Sad",
    "Losing My Religion": "Sad",
    "November Rain": "Sad",
    "Mr. Brightside": "Sad",
    "Every Breath You Take": "Sad",
    "Wish You Were Here": "Sad",
    "Paint It, Black": "Angry",
    "Angie": "Sad",
    "Tears in Heaven": "Sad",
    "The River": "Sad",
    "More Than Words": "Sad",
    "The Scientist": "Sad",
    "Creep": "Sad",
    "Fix You": "Sad",
    "Mad World": "Sad",
    "Uninvited": "Sad",
    "Black Hole Sun": "Sad",
    "Torn": "Sad",
    "Hurt": "Sad",
    "Eleanor Rigby": "Sad",
    "I Will Always Love You": "Sad",
    "Landslide": "Sad",
    "Everybody Hurts": "Sad",
    "How to Save a Life": "Sad",
    "I Don't Want to Miss a Thing": "Sad",
    "Nothing Compares 2 U": "Sad",
    "The Sound of Silence": "Sad",
    "Tears of Heaven": "Sad",
    "Stairway to Heaven": "Sad",
    "Fast Car": "Sad",
    "Yesterday": "Sad",
    "My Heart Will Go On": "Sad",
    "Total Eclipse of the Heart": "Sad",
    "Love Hurts": "Sad",
    "Yesterday Once More": "Sad",
    "Cat's in the Cradle": "Sad",
    "Wish You Were Here": "Sad",
    "Hallelujah": "Sad",
    "Whiskey Lullaby": "Sad",
    "Adams Song": "Sad",
    "Vincent": "Sad",
    "Behind Blue Eyes": "Sad",
    "Space Oddity": "Sad",
    "Sound of Silence": "Sad",
    "Everybody Hurts": "Sad",
    "Last Kiss": "Sad",
    "Mad World": "Sad",
    "Concrete Angel": "Sad",
    "What Hurts The Most": "Sad",
    "The River": "Sad",
    "The Dance": "Sad",
    "Uninvited": "Sad",
    "The Little Girl": "Sad",
    "Hurt": "Sad",
    "If You're Reading This": "Sad",
    "I Drive Your Truck": "Sad",
    "Whiskey Lullaby": "Sad",
    "Holes in the Floor of Heaven": "Sad",
    "I Don't Dance": "Sad",
    "He Stopped Loving Her Today": "Sad",
    "Concrete Angel": "Sad",
    "Go Rest High on That Mountain": "Sad",
    "Just Another Day in Paradise": "Sad",
    "Three Wooden Crosses": "Sad",
    "If I Die Young": "Sad",
    "Heaven Was Needing a Hero": "Sad",
    "You Should Be Here": "Sad",
    "Tears in Heaven": "Sad",
    "Whiskey Lullaby": "Sad",
    "If Heaven Wasn't So Far Away": "Sad",
    "I Will Always Love You": "Sad",
    "Holes in the Floor of Heaven": "Sad",
    "Dance With My Father": "Sad",
    "How Do You Get That Lonely": "Sad",
    "Concrete Angel": "Sad",
    "Don't Take the Girl": "Sad",
    "I'm Gonna Miss Her": "Sad",
    "He Didn't Have to Be": "Sad",
    "Then They Do": "Sad",
    "One More Day": "Sad",
    "Just Fishin'": "Sad",
    "You Should Be Here": "Sad",
    "The Baby": "Sad",
    "My Front Porch Looking In": "Sad",
    "The Little Girl": "Sad",
    "Sissy's Song": "Sad",
    "Drink a Beer": "Sad",
    "Just to See You Smile": "Sad",
    "Letter to Me": "Sad",
    "The Dance": "Sad",
    "Don't Blink": "Sad",
    "How Do You Like Me Now?!": "Sad",
    "I Loved Her First": "Sad",
    "Angry All The Time": "Sad",
    "Red Ragtop": "Sad",
    "The House That Built Me": "Sad",
    "Something Like That": "Sad",
    "I Hope You Dance": "Sad",
    "I Drive Your Truck": "Sad",
    "Before He Cheats": "Angry",
    "I Will Always Love You": "Sad",
    "My Immortal": "Sad",
    "How Do I Live": "Sad",
    "Amazed": "Sad",
    "When I Said I Do": "Happy",
    "Breathless": "Sad",
    "It's Your Love": "Happy",
    "Landslide": "Sad",
    "The Keeper of the Stars": "Sad",
    "Love Story": "Happy",
    "Then": "Sad",
    "Keeper of the Stars": "Sad",
    "Breathe": "Sad",
    "Unanswered Prayers": "Sad",
    "There Goes My Life": "Happy",
    "The Dance": "Sad",
    "I Cross My Heart": "Happy",
    "Cowboy Take Me Away": "Happy",
    "The Keeper of the Stars": "Sad",
    "Better Life": "Happy",
    "Austin": "Happy",
    "Just to See You Smile": "Sad",
    "I'm Already There": "Sad",
    "She's Everything": "Happy",
    "Check Yes or No": "Happy",
    "It's Your Love": "Happy",
    "My Front Porch Looking In": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "I Cross My Heart": "Happy",
    "Don't Take the Girl": "Sad",
    "I Swear": "Happy",
    "The Dance": "Sad",
    "The House That Built Me": "Sad",
    "My Best Friend": "Happy",
    "She's Everything": "Happy",
    "Then": "Sad",
    "To Make You Feel My Love": "Sad",
    "Me and You": "Happy",
    "I Hope You Dance": "Sad",
    "When You Say Nothing at All": "Happy",
    "I'm Already There": "Sad",
    "Keeper of the Stars": "Sad",
    "Don't Blink": "Sad",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "She's My Kind of Rain": "Happy",
    "My Front Porch Looking In": "Sad",
    "I Melt": "Happy",
    "I Swear": "Happy",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Austin": "Happy",
    "Just to See You Smile": "Sad",
    "The Keeper of the Stars": "Sad",
    "Amazed": "Sad",
    "I Hope You Dance": "Sad",
    "Bless the Broken Road": "Happy",
    "I Swear": "Happy",
    "It's Your Love": "Happy",
    "I'm Already There": "Sad",
    "She's My Kind of Rain": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Don't Take the Girl": "Sad",
    "Forever and Ever Amen": "Happy",
    "Then": "Sad",
    "I Hope You Dance": "Sad",
    "The Dance": "Sad",
    "She's Everything": "Happy",
    "She's My Kind of Rain": "Happy",
    "It's Your Love": "Happy",
    "Amazed": "Sad",
    "My Best Friend": "Happy",
    "My Front Porch Looking In": "Sad",
    "I Swear": "Happy",
    "Check Yes or No": "Happy",
    "Austin": "Happy",
    "Then": "Sad",
    "I Hope You Dance": "Sad",
    "Don't Blink": "Sad",
    "I'm Already There": "Sad",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "Forever and Ever Amen": "Happy",
    "My Best Friend": "Happy",
    "My Front Porch Looking In": "Sad",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",
    "It's Your Love": "Happy",
    "My Best Friend": "Happy",
    "The Dance": "Sad",
    "She's My Kind of Rain": "Happy",
    "I Swear": "Happy",
    "Then": "Sad",
    "I'm Already There": "Sad",
    "Austin": "Happy",
    "Don't Blink": "Sad",
    "I Hope You Dance": "Sad",
    "Forever and Ever Amen": "Happy",
    "When You Say Nothing at All": "Happy",
    "There Goes My Life": "Happy",
    "She's Everything": "Happy",
    "My Front Porch Looking In": "Sad",
    "My Best Friend": "Happy",
    "Check Yes or No": "Happy",
    "Amazed": "Sad",}

def suggest_song(emotion):
    emotion_songs = [song for song, e in songs.items() if e == emotion]
    if emotion_songs:
        return random.choice(emotion_songs)
    else:
        return "Sorry, no songs found for that emotion."

if __name__ == "__main__":
    print("Welcome to the Song Emotion Suggester!")
    user_emotion = input("Enter your current emotion (e.g., Happy, Sad, Excited): ")
    suggested_song = suggest_song(user_emotion)
    print(f"We suggest: {suggested_song}")
